/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef _Included_AsrFix_
#define _Included_AsrFix_

#include <string>

#if defined MAKING_LIB
  #define DLL_PUBLIC
  #define DLL_LOCAL
#else
  #if defined _WIN32 || defined __CYGWIN__
    #ifdef MAKING_DLL
      #ifdef __GNUC__
        #define DLL_PUBLIC __attribute__((dllexport))
      #else
        #define DLL_PUBLIC __declspec(dllexport) // Note: actually gcc seems to also supports this syntax.
      #endif
    #else
      #ifdef __GNUC__
        #define DLL_PUBLIC __attribute__((dllimport))
      #else
        #define DLL_PUBLIC __declspec(dllimport) // Note: actually gcc seems to also supports this syntax.
      #endif
    #endif
    #define DLL_LOCAL
  #else
    #if __GNUC__ >= 4
      #define DLL_PUBLIC __attribute__ ((visibility("default")))
      #define DLL_LOCAL  __attribute__ ((visibility("hidden")))
    #else
      #define DLL_PUBLIC
      #define DLL_LOCAL
    #endif
  #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

DLL_PUBLIC int init(const char* uri, short port,void** asrservicedata);

DLL_PUBLIC int start(const char* domain, const char* sentence, const char* filename,void* asrservicedata);

DLL_PUBLIC int stop(void* asrservicedata);

DLL_PUBLIC int recognize(const char* wavdata, int len,void* asrservicedata);

DLL_PUBLIC void release(void** asrservicedata);


#ifdef __cplusplus
}
#endif
DLL_PUBLIC char* getResult(void* asrservicedata);
#endif
